Refactor: 와일드 카드 대신 Form을 반환하도록 수정
BT2F/queosk-back pull request #106
Opened 2023-09-02 07:21 UTC by peppone-choi

### 작업 내용
와일드 카드 대신 Form을 반환하도록 수정

### 변경 사항(추가시엔 추가사항)
와일드 카드 대신 Form을 반환하도록 수정하였습니다.
Form들을 추가하였습니다.

### 특이 사항
꼼꼼히 확인 부탁드립니다.

2023-09-02 10:38 UTC, HyunsooZo submitted a review, later dismissed
수정사항 잘 확인했습니다.
좋은작업을 해주셔서 감사합니다.

2023-09-02 21:44 UTC, jodonghyeon3 requested changes
답글내용 한번 확인 부탁드립니다!!

2023-09-02 21:44 UTC, jodonghyeon3 commented on src/main/java/com/bttf/queosk/controller/CommentController.java
>          return ResponseEntity.status(HttpStatus.CREATED).build();
병호님 저희 Controller 에서 반환 되는 값을
return ResponseEntity.status(HttpStatus.OK) -> return ResponseEntity.status(OK)
static import 문을 통해서 이렇게 하도록 통일 하지 않았었나요?? 다시한번 확인 부탁드릴게요
다른 Controller부분에서도 이런식으로 되있는 부분이 많네요

2023-09-03 05:57 UTC, peppone-choi commented on src/main/java/com/bttf/queosk/controller/CommentController.java
>          return ResponseEntity.status(HttpStatus.CREATED).build();
확인 한 결과 제가 작업한 부분에서 일부 나와서 푸시 하겠습니다.
조언 감사합니다.

2023-09-03 18:33 UTC, HyunsooZo approved these changes

2023-09-03 18:42 UTC, jodonghyeon3 approved these changes

2023-09-04 04:02 UTC, merged