Refactor: Controller 반환값 와일드카드가 아닌 실제반환 Dto사용, InnerClass를 활용한 Dto 수정 
BT2F/queosk-back pull request #109
Opened 2023-09-02 14:16 UTC by HyunsooZo

### 작업 내용
- Menu 관련 Dto 통합 및 Inner Class 로 변경
- ResponseEntity 와일드카드 대신 반환되는 Dto 사용하도록 수정
### 변경 사항(추가시엔 추가사항)
- Menu와 관련된 Dto 수정
- MenuController 의 ResponseEntity<?> -> ResponseEntity<반환될 Dto> 로 수정
### 특이 사항
- 없습니다. 리뷰 잘 부탁드립니다.

2023-09-02 16:47 UTC, peppone-choi submitted a review, later dismissed

2023-09-02 22:23 UTC, jodonghyeon3 requested changes
고생하셨습니다!
리뷰 확인 부탁드리겠습니다!!

2023-09-02 22:23 UTC, jodonghyeon3 commented on src/main/java/com/bttf/queosk/controller/RefreshTokenController.java
> +        return ResponseEntity.ok(TokenRefreshForm.Response.of(tokenRefreshDto));
현수님 저희 return ResponseEntity.status(OK) 
status 사용하기로 했는데 다른 부분은 다 수정을 잘해주셨는데 이 부분은 놓치신것같아요 확인 부탁드리겠습니다!!

2023-09-03 03:00 UTC, HyunsooZo commented on src/main/java/com/bttf/queosk/controller/RefreshTokenController.java
> +        return ResponseEntity.ok(TokenRefreshForm.Response.of(tokenRefreshDto));
아 넵넵 그부분 수정하겠습니다!

2023-09-03 16:02 UTC, jodonghyeon3 approved these changes

2023-09-03 17:27 UTC, peppone-choi approved these changes

2023-09-03 18:32 UTC, merged