Feat: 주문 관련 API 구현 및 테스트
BT2F/queosk-back pull request #64
Opened 2023-08-23 11:58 UTC by peppone-choi

### 작업 내용
주문 관련 API 구현 및 테스트

### 변경 사항(추가시엔 추가사항)
주문 관련 API 구현 및 테스트

### 특이 사항
없음

### 관련 이슈(옵셔널)
이 PR과 관련된 이슈 번호

2023-08-23 18:53 UTC, HyunsooZo approved these changes
코드리뷰 요약:
- 네이밍과 코드 구조가 일관적이어서 동작에 대한 예측이 쉽고 의미전달이 잘 되는 것 같습니다. 
- JPA사용시 중복된 조회를 줄인다면 성능상의 이점이 높아질 것 같습니다.
- 좋은 코드를 작성해주셔서 감사합니다!!

2023-08-23 18:53 UTC, HyunsooZo commented on queosk/src/main/java/com/bttf/queosk/service/orderservice/OrderService.java
> +
코드 잘 보았습니다. 다만 Menu Entity에는 RestaurantId 필드가 있습니다. 
menuRepository.findByIdAndRestaurantId() 를 사용해
1. 데이터베이스의 검색 쿼리를 최적화하고
2. 중복 검색을 피하여 성능또한 높일 수 있을 것 같습니다.

2023-08-23 18:53 UTC, HyunsooZo commented on queosk/src/test/java/com/bttf/queosk/service/orderservice/OrderServiceTest.java
테스트 목적에 부합하게 잘 작성된 것으로 보입니다! 
테스트 목적과 확인하고자 하는 부분이 명확해서 좋았습니다.

2023-08-23 18:53 UTC, HyunsooZo commented on queosk/src/main/java/com/bttf/queosk/repository/OrderRepository.java
> +    List<Order> findAllByRestaurantAndStatus(OrderStatus orderStatus, Restaurant restaurant);
`findAll` 메서드는 주로 **_"특정 조건 없이"_** 엔티티의 전체 목록을 조회하는데 사용되는 것으로 알고있습니다. 
`findByRestaurantAndCreatedAtBetween`와 `findAllByRestaurantAndCreatedAtBetween` 의 동작 결과는 같겠지만 
개인적인 의견으로는  `findBy`(조건에 맞는 엔티티를 찾아라)를 쓰면 보다 직관적일 수 있을 것 같습니다.!

2023-08-23 18:53 UTC, HyunsooZo commented on queosk/src/main/java/com/bttf/queosk/controller/OrderController.java
전체적으로 매우 깔끔하고 가독성이 좋은 것 같습니다.
네이밍과 코드 구조도 일관적이어서 동작에 대한 예측이 쉽고 의미전달이 잘 되는것 같아요

2023-08-23 18:53 UTC, HyunsooZo commented on queosk/src/main/java/com/bttf/queosk/dto/orderdto/CreateOrderForm.java
> +    private Long count;
사소한 부분이지만,  `Long` 데이터타입은 `Integer` 타입에 비해 메모리 사용량이 조금 더 크며, 
값 비교 등에 약간의 성능 영향을 줄 수 있습니다.
`count`의 경우 `Integer`로 충분히 커버 가능할 것 같습니다. 
다만 위에 말씀드렸다시피 사소한 부분이니 그냥 참고만 부탁드립니다!

2023-08-24 08:25 UTC, peppone-choi commented
PR의 조언들을 다 수용하였습니다. 다시 Approve해주시면 감사하겠습니다...

2023-08-24 09:21 UTC, HyunsooZo approved these changes

2023-08-24 10:37 UTC, jodonghyeon3 approved these changes
코드 작성하시느라 고생 많으셨습니다.
좋은 코드 작성 감사합니다!!

2023-08-24 10:37 UTC, jodonghyeon3 commented on queosk/src/main/java/com/bttf/queosk/controller/OrderController.java
> +        return ResponseEntity.status(204).build();
제가 정확한 건지는 잘 모르겠는데 저도 어디서 봐서 controller 메소드에서는 동사는 뒤쪽에다 붙이는 걸로 알고있는데
https://cocobi.tistory.com/27 
혹시 이 부분 확인해주시겠어요.

2023-08-24 10:37 UTC, jodonghyeon3 commented on queosk/src/main/java/com/bttf/queosk/entity/Order.java
> +    private int count;
제가 알기로는 DB에 저장할 때는 Wrapper 타입인 Integer 나 Long타입을 저장하는것이 좋다고합니다 !!

2023-08-24 10:37 UTC, jodonghyeon3 commented on queosk/src/main/java/com/bttf/queosk/repository/OrderRepository.java
> +    List<Order> findByRestaurantAndCreatedAtBetween(Restaurant restaurant, LocalDateTime startDateTime, LocalDateTime endDateTime);
와 이렇게도 사용이 가능하군요 !! 하나배웠습니답

2023-08-25 07:14 UTC, jodonghyeon3 requested changes
코드 작성하느라 고생많으셨습니다.!
form과 dto에 있는 int 타입 확인 부탁드리겠습니다.!

2023-08-25 07:14 UTC, jodonghyeon3 commented on queosk/src/main/java/com/bttf/queosk/dto/orderdto/CreateOrderForm.java
> +    private int count;
count 도 Integer로 해야되지 않을까요??

2023-08-25 07:14 UTC, jodonghyeon3 commented on queosk/src/main/java/com/bttf/queosk/dto/orderdto/OrderDto.java
> +    private int count;
이 부분도 동일합니답

2023-08-25 07:21 UTC, peppone-choi commented on queosk/src/main/java/com/bttf/queosk/controller/OrderController.java
> +        return ResponseEntity.status(204).build();
해당사항은 나중에 리팩토링 시 참조하겠습니다!

2023-08-25 07:24 UTC, jodonghyeon3 approved these changes

2023-08-25 07:26 UTC, jodonghyeon3 approved these changes
고생하셨습니다.!!

2023-08-25 09:51 UTC, HyunsooZo submitted a review, later dismissed

2023-08-25 10:25 UTC, merged